name: Trigger All Workflows

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  batch1:
    uses: ./.github/workflows/all_1.yml
  batch2:
    uses: ./.github/workflows/all_2.yml
  batch3:
    uses: ./.github/workflows/all_3.yml
  batch4:
    uses: ./.github/workflows/all_4.yml
