name: arrayexpressbigg Testing

on:
  push:
    branches:
      - main
    paths:
      - src/bioservices/arrayexpressbigg.py
  pull_request:
    branches-ignore: []
    paths:
      - src/bioservices/arrayexpressbigg.py
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.9, 3.7, 3.8]
      fail-fast: false


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install the package itself and dependencies
      run: |
          pip install .
          pip install -r requirements_dev.txt

    - name: Test with pytest
      run: |
        pytest -n 1  --cov-report term --cov=bioservices.arrayexpressbigg test/webservices/test_arrayexpressbigg.py

