name: panther Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/bioservices/panther.py
  pull_request:
    branches-ignore: []
    paths:
      - src/bioservices/panther.py
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.8, 3.9,'3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install the package itself and dependencies
      run: |
          pip install poetry
          poetry install --with dev

    - name: Test with pytest
      run: |
        poetry run pytest -n 1  --cov-report term --cov=bioservices.panther test/webservices/test_panther.py



